### ISSUE TITLE
Prepare for 2.3

### ISSUE THREAD

**Issue by amercader** [pduchesne/ckanext-geoview#2]
@pduchesne I'm setting some time aside to review this and make it ready for CKAN 2.3. I started working on my fork (https://github.com/amercader/ckanext-geoview) with the intention to move it to the ckan github organization once it's ready. Are you happy with this? Of course you and others would be set up as admins for it.

Just a couple of questions.

* Am I right in that you need to replicate the `resource_proxy` functionality locally because the core one will ignore the parameters being sent? eg `?service=WMS&request=GetCapabilities`

* You mentioned on ckan/ckanext-spatial#84 that you had been previously working on an OpenLayers 3 version. Do you think it will be worth upgrading, as OL 3 is the latest version, or is it too much work?

**Comment by amercader** [comment]
cc @davidread

**Comment by pduchesne** [comment]
yes @amercader , that's fine by me.

you're right, the reason for the proxy is support of parameters, and more specifically of POST requests with a body (WFS GetFeature reqs).

As for OL3 : yes, I think it is worth upgrading, but regarding the effort, i can't tell easily because there are some custom connectors (ESRI stuff, Google FT) for which I need to take a deeper look to evaluate the migration cost.
It's on my todo list, but not on the top at the moment unfortunately.

**Comment by amercader** [comment]
cool, I'll crack on and keep you posted

**Comment by amercader** [comment]
@pduchesne I've finally got time to polish and publish your viewer as a separate extension:

https://github.com/ckan/ckanext-geoview

You should have got an invite for becoming an admin (@davidread I assume that you already have access as member of the ckan org).

Many thanks for this!
